[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/"
  to = "https://business.jakpat.net/for-universities"
  status = 301
  force = true

[[redirects]]
  from = "/submit-survey/*"
  to = "/submit-survey/index.html"
  status = 200
