[site]
bucket = "./dist"
entry-point = "."
pages_build_output_dir = "dist"

[site.static]
include = ["_headers", "_redirects"]

[env.production]
name = "jakpatforuniv-submit"
route = "submit.jakpatforuniv.com/*"

[build]
command = "npm run build"
output_dir = "dist"

# Routes configuration
[[routes]]
pattern = "/*"
script = "index.html"

[[routes]]
pattern = "/"
url = "https://business.jakpat.net/for-universities"
status = 301

# Ensure environment variables are accessible to Cloudflare Functions
[vars]
# These will be populated from the Cloudflare dashboard or CLI
# VITE_MAYAR_API_KEY = ""
# VITE_MAYAR_WEBHOOK_TOKEN = ""
# VITE_SUPABASE_URL = ""
# VITE_SUPABASE_ANON_KEY = ""
