[site]
bucket = "./dist"
entry-point = "."
pages_build_output_dir = "dist"

[site.static]
include = ["_headers", "_redirects"]

[env.production]
name = "jakpatforuniv-submit"
route = "submit.jakpatforuniv.com/*"

[build]
command = "npm run build"
output_dir = "dist"

[routes]
pattern = "/*"
script = "index.html"
