name = "jakpatforuniv"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./"

# Static site configuration - no build step needed
[build]
command = ""

# Serve static files only
[[rules]]
include = ["*.html", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.svg", "*.ico", "*.css", "*.js"]
exclude = ["multi-step-form/**", "node_modules/**", "survey-extractor-*/**", "src/**", "*.ts", "*.tsx"]